name: Youtube Cards

on:
  schedule:
    # Runs at 2:17 AM UTC (3:17 AM Swiss time)
    # Much more likely to start instantly because the queue is empty.
    - cron: '17 2 * * *'
  workflow_dispatch: # Allows manual run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCqrA3OS3Gf5g6NpKHrGqrew
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          max_videos: 3
